name: Archive LeetCode

run-name: Archive LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  AUTHOR: ${{ github.actor }}
  AUTHOR_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
  LEETCODE_COOKIE: ${{ secrets.LEETCODE_COOKIE }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Yarn environment
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependency
        run: yarn install
      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Setup repository
        run: |
          git clone https://${{ secrets.LEETCODE_REPOSITORY_ACCESS_TOKEN }}@github.com/ZeroGazer/leetcode leetcode
      - name: Run script
        run: yarn start
